name: 'orders_dbt'
version: '1.0.0'

profile: 'orders_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  orders_dbt:

    silver:
      stage:
        +schema: silver_stage

      core:
        +schema: silver_core

    gold:
      +schema: gold

    export:
      +schema: export
