version: 2

models:
  - name: fct_orders
    description: "Validated business-ready orders"

    columns:
      - name: order_id
        data_tests:
          - not_null
          - unique

      - name: customer_id
        data_tests:
          - not_null

      - name: currency
        data_tests:
          - accepted_values:
              arguments:
                values: ['EUR', 'USD', 'GBP']
