name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dbt Databricks
        run: pip install dbt-databricks==1.12.5

      - name: Check required files exist
        run: |
          test -f notebooks/00_LANDING_ORDERS.ipynb
          test -f notebooks/01_BRONZE_ORDERS.ipynb

          test -f orders_dbt/models/silver/stage/stg_orders/stg_orders.sql
          test -f orders_dbt/models/silver/stage/stg_orders/stg_orders.yml

          test -f orders_dbt/models/silver/core/core_orders/core_orders.sql
          test -f orders_dbt/models/silver/core/core_orders/core_orders.yml

          test -f orders_dbt/models/silver/core/rejected_orders/rejected_orders.sql
          test -f orders_dbt/models/silver/core/rejected_orders/rejected_orders.yml

          test -f orders_dbt/models/gold/gold_orders/gold_orders.sql
          test -f orders_dbt/models/gold/gold_orders/gold_orders.yml

          test -f orders_dbt/models/export/export_orders_completed/export_orders_completed.sql
          test -f orders_dbt/models/export/export_orders_completed/export_orders_completed.yml

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt

          cat > ~/.dbt/profiles.yml <<EOF
          orders_dbt:
            target: dev

            outputs:
              dev:
                type: databricks
                catalog: workspace
                schema: dev
                host: ${DATABRICKS_HOST}
                http_path: /sql/1.0/warehouses/cfd3eec10376b45e
                token: ${DATABRICKS_TOKEN}
                threads: 4
          EOF

      - name: Validate dbt project
        working-directory: orders_dbt
        run: dbt parse --target dev

      - name: Compile dbt project
        working-directory: orders_dbt
        run: dbt compile --target dev
