name: Deploy PROD

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate PROD bundle
        run: databricks bundle validate -t prod

      - name: Deploy Databricks bundle to PROD
        run: databricks bundle deploy -t prod
