name: Deploy PROD

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dbt Databricks
        run: pip install dbt-databricks==1.12.5

      - name: Validate PROD bundle
        run: databricks bundle validate -t prod

      - name: Deploy Databricks bundle to PROD
        run: databricks bundle deploy -t prod

      - name: Create dbt PROD profile
        run: |
          mkdir -p ~/.dbt

          cat > ~/.dbt/profiles.yml <<EOF
          orders_dbt:
            target: prod

            outputs:
              prod:
                type: databricks
                catalog: workspace
                schema: prod
                host: ${DATABRICKS_HOST}
                http_path: /sql/1.0/warehouses/cfd3eec10376b45e
                token: ${DATABRICKS_TOKEN}
                threads: 4
          EOF

      - name: Build dbt models in PROD
        working-directory: orders_dbt
        run: dbt build --target prod
